name: Publish to PyPica

on:
  pull_request:
    paths:
      - '**.py'
  workflow_dispatch: ~

permissions:
  contents: write

jobs:
  tests:
    name: "Run tests"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with pytest
        run: |
          pytest --ignore=tests/example.py --doctest-modules --junitxml=junit/test-results.xml